# Generated by Django 4.0.6 on 2022-07-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, default='')),
                ('status', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(related_name='tasks', to='to_do_list_app.tags')),
            ],
        ),
    ]
