# Generated by Django 4.0.6 on 2022-07-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status']},
        ),
    ]
