# Generated by Django 4.0.6 on 2022-07-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0003_alter_task_options_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', '-datetime']},
        ),
    ]
